language: ko-KR # 언어 설정

early_access: true # 미리보기 기능 활성화
enable_free_tier: true # 프리 티어 활성화
auto_resolve_threads: false # 자동 해결 비활성화

reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai 요약'
  auto_title_placeholder: '@coderabbitai'
  poem: true
  review_status: true
  collapse_walkthrough: false

  path_filters:
    - "!**/swagger.json"
    - "!**/README.md"

  abort_on_close: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [ ]
    labels: [ ]
    drafts: false
    base_branches: [ "develop" ]

  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      disabled_rules:
        - EN_UNPAIRED_BRACKETS
        - EN_UNPAIRED_QUOTES
      disabled_categories:
        - TYPOS
        - TYPOGRAPHY
        - CASING
      enabled_only: false
      level: default
      enabled_rules: [ ]
      enabled_categories: [ ]
    biome:
      enabled: false
    hadolint:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    ast-grep:
      packages: [ ]
      rule_dirs: [ ]
      util_dirs: [ ]
      essential_rules: true

chat:
  enabled: true
  max_token_length: 4096

knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: [ ] # 필요한 경우 Jira 프로젝트 키 추가
  docs:
    spring_references: # Spring 관련 문서 참조 추가
      enabled: true
      urls:
        - 'https://docs.spring.io/spring-boot/docs/current/reference/html/'
        - 'https://docs.spring.io/spring-framework/docs/current/reference/html/'

# Spring 특화 설정
spring_specific:
  tech_stack:
    - java
    - spring-boot
    - spring-data
    - spring-security
    - hibernate
  testing_frameworks:
    - junit5
    - mockito
    - testcontainers
  review_focus:
    - 'dependency-injection-practices'
    - 'transactional-boundaries'
    - 'exception-handling'
    - 'api-design'
    - 'security-best-practices'
