FROM openjdk:17
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", \
    "-Duser.timezone=Asia/Seoul", \
    "-Djdk.internal.platform.cgroupv1.memory=false", \
    "-Djdk.internal.platform.cgroupv1.cpuset=false", \
    "-jar", "app.jar", \
    "--spring.profiles.active=dev"]
